// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QfeW8OTYDhwKI9XVqiwoQpDo7LGau_8',
    appId: '1:435881648319:web:1e14fe82c0732ab78d660a',
    messagingSenderId: '435881648319',
    projectId: 'xogame-1828c',
    authDomain: 'xogame-1828c.firebaseapp.com',
    storageBucket: 'xogame-1828c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLqaCCOQghgyO5pYElCQEz-3S3zZintw',
    appId: '1:435881648319:android:f44bc4e2268894c78d660a',
    messagingSenderId: '435881648319',
    projectId: 'xogame-1828c',
    storageBucket: 'xogame-1828c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxVtrCI2cCuTIvEysnSCfj6FotSVXGYs',
    appId: '1:435881648319:ios:900724a3b710483b8d660a',
    messagingSenderId: '435881648319',
    projectId: 'xogame-1828c',
    storageBucket: 'xogame-1828c.firebasestorage.app',
    iosBundleId: 'com.example.xoGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxVtrCI2cCuTIvEysnSCfj6FotSVXGYs',
    appId: '1:435881648319:ios:900724a3b710483b8d660a',
    messagingSenderId: '435881648319',
    projectId: 'xogame-1828c',
    storageBucket: 'xogame-1828c.firebasestorage.app',
    iosBundleId: 'com.example.xoGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4QfeW8OTYDhwKI9XVqiwoQpDo7LGau_8',
    appId: '1:435881648319:web:7fd020247f6cab9d8d660a',
    messagingSenderId: '435881648319',
    projectId: 'xogame-1828c',
    authDomain: 'xogame-1828c.firebaseapp.com',
    storageBucket: 'xogame-1828c.firebasestorage.app',
  );
}
